export const ActionType = {
  USER_DEPARTMENT_DATA: 'USER_DEPARTMENT_DATA',
  USER_FIELD_DATA: 'USER_FIELD_DATA',
  USER_CONTACT_DATA: 'USER_CONTACT_DATA',
  USER_COMPANY_DATA: 'USER_COMPANY_DATA',
  USER_DATA_NAME: 'USER_DATA_NAME',
};
